/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Xue.Zhao' at '9/26/16 10:51 AM' with Gradle 2.14.1
 *
 * @author Xue.Zhao, @date 9/26/16 10:51 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
